title: Abu Md Alamgir Hassan
logo: /Picture/Abu_Hassan.png
description: Data Analyst
navbar-links:
About Me: "Resume"
show_download: true
theme: jekyll-theme-minimal
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"
